# Generated by Django 3.1 on 2020-08-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0003_auto_20200828_1401'),
        ('follow', '0002_auto_20200828_1402'),
    ]

    operations = [
    ]
