# Generated by Django 3.1 on 2020-08-27 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('follow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('followers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='follow.follower')),
                ('following', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='follow.following')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
