# Generated by Django 3.1 on 2020-08-27 18:18

from django.db import migrations, models
import django.db.models.deletion
import project.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='follow.follower'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='follow.following'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=project.utils.utils.upload_directory_path),
        ),
    ]
