# Generated by Django 3.1 on 2020-08-28 07:07

from django.db import migrations, models
import project.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200828_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=project.utils.utils.upload_directory_path),
        ),
        migrations.AlterField(
            model_name='postextraimage',
            name='image',
            field=models.ImageField(upload_to=project.utils.utils.upload_directory_path),
        ),
    ]
