# Generated by Django 3.1 on 2020-08-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200828_0935'),
        ('post', '0005_auto_20200828_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_likes',
            field=models.ManyToManyField(blank=True, default=False, related_name='likes', to='profiles.Profile'),
        ),
    ]
