# Generated by Django 3.1 on 2020-08-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200828_1402'),
        ('post', '0009_auto_20200828_1356'),
    ]

    operations = [
    ]
