# Generated by Django 3.1 on 2020-08-28 12:35

from django.db import migrations, models
import project.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_merge_20200828_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=project.utils.utils.generate_slug, null=True, unique=True),
        ),
    ]
